openapi: 3.0.0
info:
  version: "1.0-oas3"
  title: arcus Merchant Documentation
  description: |
    # Introduction

    This documentation provides Merchants the protocol to be implemented in
    order to receive an xChange request.

    After implementation, Merchants will be able to receive updated card
    information from Arcus Issuer partners, which will reduce the possibility of
    a false positive occurring from outdated payment information.

    The actual update occurs in the following steps:
    1. Merchant system receives a request from Arcus infrastructure in real-time.
    2. Merchant updates the payment card information in their infrastructure,
    using the payload previously delivered by Arcus
    3. Merchant provides a response code to Arcus infrastructure, which Arcus
    will forward to our Issuer partner.

    ## Types of Integrations With Arcus

    * __Merchant Integrates with Arcus__: Merchant can use this documentation to
    create an API integration with the Arcus infrastructure.
    * __Arcus Integrates with Merchant__: Arcus is able to integrate with
    existing Merchant API infrastructure in order to eliminate level of effort
    required to go live with Arcus xChange. To accomplish this, Arcus works with
    the Merchant to map our data to existing API endpoints for card information.
      * If interested in discussing further, please contact your Arcus
        representative to learn more.

    ---

    # Environments

    Arcus will provide Merchants with separate API keys for our two existing
    environments:

    * __Sandbox__: Arcus maintains a Sandbox which allows developers to test the
    API using mock data. We recommend keeping the following information in mind:
        * The data is always fake
        * Do not send any real information in the Sandbox
        * To make requests to the sandbox environment, use the following URL: https://apix.staging.arcusapi.com
    * __Production__: Once you have completed all of the necessary tests in the
    sandbox, contact us to receive your production keys.
        * To make requests to the production environment, use the following URL: https://apix.arcusapi.com
    * __NOTE__: For security reasons, it's not possible to make production
    requests through our dynamic documentation.


    ---

    # Security

    To make requests to our endpoints, you must use the `https` protocol,
    regardless of the environment you're using.

    __Note:__ For security reasons, our API doesn't support TLS V1.0;
    we ask that you use minimum TLS v1.2.

    ## Authentication

    Arcus supports multiple methods of authentication, including:
    * Mutual SSL
    * Authorization Token
    * OAuth

    ---

    # Order of Operations:

    * Arcus facilitates the transfer of new PCI and PII from Issuer environment,
    to Merchant environment.
    * The Merchant receives the payload, and is responsible for enriching
    appropriate Merchant infrastructure endpoints in real time.
    * The Merchant is then expected to return a status to Arcus in order to
    allow Arcus to notify customer of update success.

    ___

tags:
  - name: xChange
    description: Access to xChange documentation
paths:
  /cards:
    put:
      tags:
        - xChange
      summary: Receive a migration request.
      operationId: putCard
      description: |
        This endpoint allows Arcus to push to the Merchant infrastructure a
        migration request.

        __Identity Authentication Methods:__
        * Customer identity authentication method depends on Merchant
        tokenization method.
        * __PAN__: Arcus sends Old Card Information as identifier
        * __Credentials__: Arcus sends customer account credentials as identifier

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - merchant_id
                - card_first_name
                - card_last_name
                - card_type
                - card_brand
                - card_number
                - card_expiration
                - card_verification_code
                - card_address
                - card_city
                - card_state
                - card_zip_code
                - card_country
              properties:
                id:
                  type: string
                  description: >-
                    The request's ID, to uniquely identify the request. An UUID
                    format v4.
                  example: 6ab564f9-4e9d-4b03-96d6-dd9f2c39ec53
                version:
                  type: integer
                  description: 'The version used to identify the payload (Must be: 1)'
                  example: 1
                payload:
                  type: object
                  description: The paylaod containing all the Migration information
                  properties:
                    type:
                      type: string
                      description: >-
                        The authentication type associated to the merchant. The values accepted are:
                        `credentials` or `old_pan`.
                      example: credentials
                    old_pan:
                      type: string
                      description: >-
                        Old Card Information as identifier. Only required if `type` is equal to `old_pan`
                      example: "5186822726831300"
                    login:
                      type: string
                      description: >-
                        The User's login allowing you to find him in your
                        Database. Only required if `type` is equal to `credentials`.
                      example: john@mail.com
                    password:
                      type: string
                      description: The User's password allowing to authenticate the login. Only required if `type` is equal to `credentials`.
                      example: Life42!
                    name_on_card:
                      type: string
                      description: The full name of the card holder
                      example: John Smith
                    card_brand:
                      type: string
                      description: >-
                        The brand of the card
                        (visa/mastercard/american_express/discover)
                      example: american_express
                    card_number:
                      type: string
                      description: >-
                        The FPAN or DPAN of the card (without spaces or
                        formatting)
                      example: '344135254976623'
                    card_security:
                      type: string
                      description: The CVV of the card (3 or 4 digits)
                      example: '0123'
                    card_expiration:
                      type: object
                      description: The expiration object of the card
                      properties:
                        month:
                          type: integer
                          description: The month from 1 to 12 of the card expiration
                          example: 4
                        year:
                          type: integer
                          description: >-
                            The year greater or equals to 2018 of the card
                            expiration
                          example: 2022
                    card_address:
                      type: object
                      description: The object for the card holder's physical address
                      properties:
                        street:
                          type: string
                          description: The street name of the Card Holder
                          example: '214W 29th St. Suite 1007 '
                        city:
                          type: string
                          description: The city name of the Card Holder
                          example: New York
                        state:
                          type: string
                          description: The US state of the Card Holder (as 2 characters)
                          example: NY
                        zipcode:
                          type: string
                          description: The zip code of the address
                          example: '10001'
                        country:
                          type: string
                          description: 'The country of the address (default: US)'
                          example: US
      responses:
        '204':
          description: Successful response - No payload expected
        '401':
          description: Credentials Invalid -- The provided credentials don't match existing records
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID sent in the initial request
                    example: 5fde398b-90b3-48f3-9012-9de7820641c3
                  message:
                    type: string
                    description: The message explaining the error
                    example: Credentials invalid
                example:
                  id: 5fde398b-90b3-48f3-9012-9de7820641c3
                  message: Credentials invalid
        '404':
          description: Unknown user - The credentials provided don't match an existing user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID sent in the initial request
                    example: 5fde398b-90b3-48f3-9012-9de7820641c3
                  message:
                    type: string
                    description: The message explaining the error
                    example: Unknown user
                example:
                  id: 5fde398b-90b3-48f3-9012-9de7820641c3
                  message: Unknown user
        '420':
          description: MFA invalid -- The MFA answer doesn't match existing records
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID sent in the initial request
                    example: 5fde398b-90b3-48f3-9012-9de7820641c3
                  message:
                    type: string
                    description: The message explaining the error
                    example: MFA invalid - The MFA answer doesn't match existing records
                example:
                  id: 5fde398b-90b3-48f3-9012-9de7820641c3
                  message: MFA invalid - The MFA answer doesn't match existing records
        '422':
          description: Card rejected -- The card information is invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID sent in the initial request
                    example: 5fde398b-90b3-48f3-9012-9de7820641c3
                  message:
                    type: string
                    description: The message explaining the error
                    example: Card rejected - The address doesn't match the card holder
                example:
                  id: 5fde398b-90b3-48f3-9012-9de7820641c3
                  message: Card rejected - The address doesn't match the card holder
        '500':
          description: >-
            Service Temporary Unavailable -- Merchant system is temporarily unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID sent in the initial request
                    example: 5fde398b-90b3-48f3-9012-9de7820641c3
                  message:
                    type: string
                    description: The message explaining the error
                    example: Service Temporary Unavailable
                example:
                  id: 5fde398b-90b3-48f3-9012-9de7820641c3
                  message: Service Temporary Unavailable
